[package]
name = "skb_config"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { version = "0.13", features = ["ini", "json", "yaml"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
log = "0.4"
env_logger = { version = "0.10", optional = true } # For tests
